chore: ensure action versions are pinned

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -16,6 +16,12 @@ on:
   workflow_dispatch: {}
 
 jobs:
+  ensure-actions-sha-pin:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+    - uses: zgosalvez/github-actions-ensure-sha-pinned-actions@c3a2b64f69b7a1542a68f44d9edbd9ec3fc1455e # v3.0.20
+
   installer-tests:
     timeout-minutes: 10
     runs-on: ubuntu-latest
@@ -236,3 +242,24 @@ jobs:
     steps:
     - name: e2e tests pased
       run: echo all e2e tests passed
+
+  # TODO: when this gets merged, e2e-tests-passed and integration-tests-passed should be removed
+  # and checks on GitHub pull requests should be updated to use this job.
+
+  # We need this step to fail the workflow if any of the previous steps failed or were cancelled.
+  # It allows to use this particular job as a required check for PRs.
+  # Ref: https://github.com/orgs/community/discussions/26822#discussioncomment-3305794
+  passed:
+    runs-on: ubuntu-latest
+    needs:
+      - ensure-actions-sha-pin
+      - unit-tests
+      - installer-tests
+      - e2e-tests
+      - integration-tests
+    if: always()
+    steps:
+      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: |
+          echo "Some jobs failed or were cancelled."
+          exit 1
